from setuptools import setup

setup(name='roach_tools',
      version='0.1',
      description='Roach tools for digital development in the MWL.',
      url='http://github.com/francocalan/roach_tools',
      author='Franco Curotto',
      author_email='francocurotto@gmail.com',
      license='GPL',
      packages=['roach_tools',
                'roach_dummies'],
      package_dir={'roach_tools' : 'experiments',
                   'roach_dummies': 'experiments/dummies'},
      scripts=['experiments/snapshot_animator.py',
               'experiments/spectra_animator.py',
               'experiments/kestfilt_animator.py',
               'utilities/get_set_clock_synth.py',
               'utilities/upload_program_roach2.py'],
      install_requires=[
            'construct', 
            'corr', 
            'katcp', 
            'numpy', 
            'matplotlib',
            'numexpr'],
      dependency_links=['https://github.com/nrao/ValonSynth'],
      zip_safe=False)
