import time
import numpy as np
from itertools import product
from multibeam_animator import MultibeamAnimator

class MultibeamAnimator64(MultibeamAnimator):
    """
    This class plots a square image of the parallel data
    of multiple beams generated by the beamformer at the
    same time.
    """
    def steer_beams(self):
        """
        Steer beams to appropate locations to create image.
        """
        angles_comb = product(self.el_angs, self.az_angs)

        print "Steering the beams for every beamformer..."
        for i in range(4):
            for j in range(4):
                for t in range(4):
                    addrs = [[i,j,t,port] for port in range(self.nports)]
                    el, az = angles_comb.next()
                    self.steer_beam(addrs, az, el)
        print "done"
