import numpy as np
from  itertools import chain
from ..animator import Animator
from ..calanfigure import CalanFigure
from beamscan_axis import BeamscanAxis
from ..spectra_animator import scale_dbfs_spec_data
from single_beamscan import singlebeam_scan

class MultibeamAnimator(Animator, SinglebeamScan):
    """
    This class plots a square image of the parallel data
    of multiple beams generated by the beamformer at the
    same time.
    """
    def __init__(self, calanfpga):
        Experiment.__init__(self, calanfpga)
        self.nports = len(list(chain.from_iterable(self.settings.array_info['el_pos']))) # flatten list)

        # beam forming parameters
        self.freq_chnl = self.settings.freq_chnl
        azr = self.settings.az_ang_range
        elr = self.settings.el_ang_range
        self.az_angs = range(azr[0], azr[1]+azr[2], azr[2])
        self.el_angs = range(elr[0], elr[1]+elr[2], elr[2])

        # figure and axis
        self.figure = CalanFigure(n_plots=1, create_gui=False)
        self.figure.create_axis(0, BeamscanAxis, (self.az_angs[0], self.az_angs[-1]), 
            (self.el_angs[0], self.el_angs[-1]), azr[2], elr[2], self.figure.fig)

        print "Steering the beams for every beamformer..."
        for i, el in enumerate(self.el_angs):
            for j, az in enumerate(self.az_angs):
                addrs = [[i,j,port] for port in range(self.nports)]
                SinglebeamScan.steer_beam(self, addrs, az, el)
        print "done"

    def get_data(self):
        """
        Get the power data from all the beamformers.
        """
        spec_data = self.fpga.get_bram_data_sync(self.settings.spec_info)
        spec_data = scale_dbfs_spec_data(self.fpga, spec_data, self.settings.spec_info)
        mbf_data = np.array(spec_data)[:,:,self.freq_chnl+4] # TODO: fix hack

        return mbf_data
